angular.module("myApp",["ui.router"])
.config(function($stateProvider,$urlRouterProvider){
  $stateProvider
  .state("home",{
    url:"/",
    templateUrl:"view/home.html"
  })
  .state("question",{
    url:"/question",
    templateUrl:"view/question.html",
    controller:"questionCtrl"
  })
  .state("answer",{
    url:"/answer/:filaName",
    templateUrl:"view/answer.html",
    controller:"answerCtrl"
  })
  .state("about",{
    url:"/about",
    templateUrl:"view/about.html",
  })
  $urlRouterProvider.otherwise("/");
})
